[[redirects]]
    from = "https://www.taxology-global.com/*"
    to = "https://taxology-global.com/:splat"
    force = true

[[redirects]]
    from = "https://taxology.nl/*"
    to = "https://taxology-global.com/:splat"
    force = true

[[redirects]]
    from = "https://www.taxology.nl/*"
    to = "https://taxology-global.com/:splat"
    force = true

[[redirects]]
    from = "https://taxolo.gy/*"
    to = "https://taxology-global.com/:splat"
    force = true

[[redirects]]
    from = "https://www.taxolo.gy/*"
    to = "https://taxology-global.com/:splat"
    force = true

[[redirects]]
    from = "https://taxologyglobal.com/*"
    to = "https://taxology-global.com/:splat"
    force = true

[[redirects]]
    from = "https://www.taxologyglobal.com/*"
    to = "https://taxology-global.com/:splat"
    force = true

[[redirects]]
    from = "https://taxology.global/*"
    to = "https://taxology-global.com/:splat"
    force = true

[[redirects]]
    from = "https://www.taxology.global/*"
    to = "https://taxology-global.com/:splat"
    force = true

[[redirects]]
    from = "https://taxology.netlify.com/*"
    to = "https://taxology-global.com/:splat"
    force = true
