default: &default
  project: taxology.nl
  repository: git@git.voormedia.com:taxology/protocol-website.git
  post_setup_script: /srv/html/post-setup.sh
  post_deploy_script: /srv/html/post-deploy.sh

preview:
  <<: *default
  domain: mab
  # branch: master
  deploy_to: /srv/html/taxology.nl-preview
  deploy_config_to: /srv/html/.cfgsrc/taxology.nl-preview
  rake_env: { WEB_ENV: preview }

acceptance:
  <<: *default
  domain: greip
  branch: master
  deploy_to: /srv/html/taxology.nl-acceptance
  deploy_config_to: /srv/html/.cfgsrc/taxology.nl-acceptance
  rake_env: { WEB_ENV: acceptance }

production:
  <<: *default
  domain: helike
  # branch: production
  deploy_to: /srv/html/taxology.nl-production
  deploy_config_to: /srv/html/.cfgsrc/taxology.nl-production
  rake_env: { WEB_ENV: production }
